### ISSUE TITLE
unable to obtain stable firefox connection in 60 seconds

### ISSUE THREAD

**Issue by lencioni** [diffux/diffux_ci#27]
I'm seeing this error sometimes when running likadan in Jenkins CI.

```
/var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.47.0/lib/selenium/webdriver/firefox/launcher.rb:90:in `connect_until_stable': unable to obtain stable firefox connection in 60 seconds (127.0.0.1:7055) (Selenium::WebDriver::Error::WebDriverError)
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.47.0/lib/selenium/webdriver/firefox/launcher.rb:55:in `block in launch'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.47.0/lib/selenium/webdriver/common/socket_lock.rb:38:in `locked'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.47.0/lib/selenium/webdriver/firefox/launcher.rb:51:in `launch'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.47.0/lib/selenium/webdriver/firefox/bridge.rb:41:in `initialize'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.47.0/lib/selenium/webdriver/common/driver.rb:50:in `new'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.47.0/lib/selenium/webdriver/common/driver.rb:50:in `for'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.47.0/lib/selenium/webdriver.rb:84:in `for'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/likadan-0.0.13/lib/likadan_runner.rb:20:in `<top (required)>'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/likadan-0.0.13/bin/likadan:13:in `require'
	from /var/lib/jenkins/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/likadan-0.0.13/bin/likadan:13:in `block in <top (required)>'
```

**Comment by lencioni** [comment]
It looks like it might be related to this: https://github.com/SeleniumHQ/selenium/issues/835

**Comment by lencioni** [comment]
It looks like some people who have run into this problem before say that [it is a problem with the headless gem](https://code.google.com/p/selenium/issues/detail?id=4967#c5), but [that issue seems to have been resolved a long time ago](https://github.com/leonid-shevtsov/headless/issues/33).

**Comment by trotzig** [comment]
@lencioni: Have you had a chance to test the retry-fix out? In case that helps, I think we should close this issue.

**Comment by lencioni** [comment]
It helps.

**Comment by lencioni** [comment]
After running with this for a while, I can say that it definitely helps, but we still see maybe a couple of failures each day. It might be worth adding another retry.

**Comment by trotzig** [comment]
I haven't seen this in a very long time now. Is it time to close this issue?

**Comment by lencioni** [comment]
Yeah, probably. Although we haven't really solved the issue--just worked around it.
